import Head from "next/head";
import Image from "next/image";
import Sidebar from "../components/Sidebar";
import Header from "../components/Header";
import styled from "styled-components";
import { useEffect, useState } from "react";
import { useRouter } from "next/router";
import Loading from "../components/Loading";
import Logo from "../components/Logo";

export default function Home() {
  const [items, setItems] = useState([]);
  const router = useRouter();

  useEffect(() => {
    fetch("https://fakestoreapi.com/products?limit=20")
      .then((response) => response.json())
      .then((json) => {
        setItems(json);
      });
  }, []);

  const pushToItemPage = (itemId) => {
    router.push(`/item/${itemId}`);
  };

  if (!items) return <Loading />;
  return (
    <>
      <Container className="lg:hidden bg-gray-200 h-screen">
        <div className="bg-white p-3">
          <Logo />
        </div>
        <div className="m-5 bg-white p-5 rounded-md shadow-md">
          <h3>Decentralized Peer to Peer eCommerce</h3>
          <p className="text-gray-400">
            Buyers and sellers both put collateral into a smart contract to
            ensure each party acts fairly. When the buyer recieves the item in
            the mail and approves that everything is okay, the collateral gets
            released back to the buyer and seller. Also the seller recieves the
            sale price held in the contract. In the case of a dispute, the buyer
            can mail back the item and when the seller recieves the items and
            approves everything is okay, the collateral gets released back to
            the seller and buyer.
          </p>
        </div>
        <div className="m-5 bg-white p-5 rounded-md">
          <h3 className="text-blue-400">Please visit out desktop version</h3>
        </div>
      </Container>
      <Container className="hidden lg:block">
        <Head>
          <title>wllo</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <div>
          <Header />
          <Body className="flex">
            <Sidebar />
            <ItemContainer className="scrollbar-hide">
              <div className="m-5 bg-white p-5 rounded-md shadow-md">
                <h3>Decentralized Peer to Peer eCommerce</h3>
                <p className="text-gray-400">
                  Buyers and sellers both put collateral into a smart contract
                  to ensure each party acts fairly. When the buyer recieves the
                  item and approves that everything is okay, the collateral gets
                  released back to the buyer and seller. Also the seller
                  recieves the sale price held in the contract. In the case of a
                  dispute, the buyer can mail back the item and when the seller
                  recieves the items and approves everything is okay, the
                  collateral gets released back to the seller and buyer.
                </p>
              </div>
              <div className="flex flex-wrap justify-center relative">
                {items.map((item) => {
                  return (
                    <div
                      key={item.id}
                      className="rounded-md shadow-md cursor-pointer bg-white p-5 m-5 flex flex-col justify-center items-center w-[300px]"
                    >
                      <img src={item.image} width={100} height={100} />
                      <h3 className="text-blue-400 text-xl p-3">
                        {item.title}
                      </h3>
                      <p>${item.price}</p>
                      <div
                        className="text-blue-400 bg-gray-200 py-2 px-5 rounded-md"
                        onClick={() => {
                          pushToItemPage(item.id);
                        }}
                      >
                        see more
                      </div>
                    </div>
                  );
                })}
              </div>
            </ItemContainer>
          </Body>
        </div>
      </Container>
    </>
  );
}

const Container = styled.div``;

const Body = styled.div`
  background-color: whitesmoke;
`;

const ItemContainer = styled.div`
  overflow: scroll;
  flex: 1;
  height: 100vh;
`;
