import styled from "styled-components";
import Header from "./Header";
import Head from "next/head";
import Sidebar from "./Sidebar";
import { Circle } from "better-react-spinkit";

function Loading() {
  return (
    <Container>
      <Head>
        <title>wllo</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <Header />
        <Body className="flex">
          <Sidebar />
          <ItemContainer className="scrollbar-hide">
            <div className="m-5 bg-white p-5 rounded-md">
              <h3>Decentralized Peer to Peer eCommerce</h3>
              <p className="text-gray-400">
                Buyers and sellers both put collateral into a smart contract to
                ensure each party acts fairly. When the buyer recieves the item
                and approves that everything is okay, the collateral gets
                released back to the buyer and seller. Also the seller recieves
                the sale price held in the contract. In the case of a dispute,
                the buyer can mail back the item and when the seller recieves
                the items and approves everything is okay, the collateral gets
                released back to the seller and buyer.
              </p>
            </div>
            <div className="flex flex-wrap justify-center relative">
              <Circle className="pt-20" size={70} />
            </div>
          </ItemContainer>
        </Body>
      </div>
    </Container>
  );
}

export default Loading;

const Container = styled.div``;

const Body = styled.div`
  background-color: whitesmoke;
`;

const ItemContainer = styled.div`
  overflow: scroll;
  flex: 1;
  height: 100vh;
`;
