import Head from "next/head";
import Image from "next/image";
import Sidebar from "../../components/Sidebar";
import Header from "../../components/Header";
import styled from "styled-components";
import { useEffect, useState } from "react";
import { useRouter } from "next/router";
import Loading from "../../components/Loading";
import Logo from "../../components/Logo";
import Banner from "../../components/Banner";

export default function Home() {
  const [item, setItem] = useState("");
  const router = useRouter();
  const { id } = router.query;

  useEffect(() => {
    fetch(`https://fakestoreapi.com/products/${id}`, {
      method: "GET",
      headers: { "Content-Type": "application/json" },
    })
      .then((response) => response.json())
      .then((response) => {
        setItem(response);
      });
  }, []);

  if (!item) return <Loading />;
  return (
    <>
      <Container className="lg:hidden bg-gray-200 h-screen">
        <Head>
          <title>dSETTLE</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/handshake.png" />
        </Head>
        <div className="bg-white p-3 flex justify-center items-center">
          <Logo />
        </div>
        <Banner />
        <div className="m-5 bg-white p-5 rounded-md">
          <h3 className="text-blue-400">Please visit out desktop version</h3>
        </div>
      </Container>
      <Container className="hidden lg:block">
        <Head>
          <title>wllo</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <div>
          <Header />
          <Body className="flex">
            <Sidebar />
            <ItemContainer className="scrollbar-hide">
              <Banner />
              <div className="flex justify-center items-center flex-col bg-white mx-5 p-10 my-5 rounded-md shadow-md">
                <div className="w-[500px] flex-wrap m-3">
                  <h3 className="text-2xl">{item.title}</h3>
                </div>

                <img
                  className="m-3"
                  src={item.image}
                  height={200}
                  width={200}
                />
                <p className="m-3 w-[400px] flex-wrap">{item.description}</p>
              </div>
            </ItemContainer>
          </Body>
        </div>
      </Container>
    </>
  );
}

const Container = styled.div``;

const Body = styled.div`
  background-color: whitesmoke;
`;

const ItemContainer = styled.div`
  overflow: scroll;
  flex: 1;
  height: 100vh;
`;
